# Generated by Django 2.2.7 on 2020-03-19 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_auto_20200319_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessondetail',
            name='breaktime',
            field=models.ForeignKey(blank=True, help_text='Choose an activity to link to for the Call to Action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Breaktime'),
        ),
    ]
