# Generated by Django 2.2.7 on 2020-03-19 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_auto_20200319_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonlist',
            name='thumb_description',
        ),
        migrations.RemoveField(
            model_name='lessonlist',
            name='thumb_image',
        ),
    ]
