# Generated by Django 2.2.7 on 2020-03-20 02:40

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_auto_20200319_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='InclassActivitySnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, help_text='A slug to identify lessons by this activity', max_length=255, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Inclass Activitiy',
                'verbose_name_plural': 'Inclass Activities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LessonUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, help_text='A slug to identify lessons by this activity', max_length=255, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lesson Unit',
                'verbose_name_plural': 'Lesson Units',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='lessondetail',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='lessondetail',
            name='custom_title',
        ),
        migrations.AlterField(
            model_name='lessondetail',
            name='breaktime',
            field=wagtail.core.fields.StreamField([('heading_block', wagtail.core.blocks.StructBlock([('headting_text', wagtail.core.blocks.CharBlock(classname='title', required=True)), ('size', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))])), ('paragraph_block', wagtail.core.blocks.RichTextBlock(icon='fa-paragraph', template='blocks/paragraph_block.html')), ('image_block', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('attribution', wagtail.core.blocks.CharBlock(required=False))])), ('block_quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock()), ('attribute_name', wagtail.core.blocks.CharBlock(blank=True, label='e.g. Mary Berry', required=False))])), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL e.g https://www.youtube.com/embed/SGJFWirQ3ks', icon='fa-s15', template='blocks/embed_block.html'))], blank=True, null=True, verbose_name='Breaktime'),
        ),
        migrations.AlterField(
            model_name='lessondetail',
            name='section_1',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Block 1'),
        ),
        migrations.AlterField(
            model_name='lessondetail',
            name='section_2',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Block 1'),
        ),
        migrations.AlterField(
            model_name='lessondetail',
            name='warmup',
            field=wagtail.core.fields.StreamField([('heading_block', wagtail.core.blocks.StructBlock([('headting_text', wagtail.core.blocks.CharBlock(classname='title', required=True)), ('size', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))])), ('paragraph_block', wagtail.core.blocks.RichTextBlock(icon='fa-paragraph', template='blocks/paragraph_block.html')), ('image_block', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('attribution', wagtail.core.blocks.CharBlock(required=False))])), ('block_quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock()), ('attribute_name', wagtail.core.blocks.CharBlock(blank=True, label='e.g. Mary Berry', required=False))])), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL e.g https://www.youtube.com/embed/SGJFWirQ3ks', icon='fa-s15', template='blocks/embed_block.html'))], blank=True, null=True, verbose_name='Warm Up'),
        ),
        migrations.AlterField(
            model_name='lessondetail',
            name='wrapup',
            field=wagtail.core.fields.StreamField([('heading_block', wagtail.core.blocks.StructBlock([('headting_text', wagtail.core.blocks.CharBlock(classname='title', required=True)), ('size', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))])), ('paragraph_block', wagtail.core.blocks.RichTextBlock(icon='fa-paragraph', template='blocks/paragraph_block.html')), ('image_block', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('attribution', wagtail.core.blocks.CharBlock(required=False))])), ('block_quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock()), ('attribute_name', wagtail.core.blocks.CharBlock(blank=True, label='e.g. Mary Berry', required=False))])), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL e.g https://www.youtube.com/embed/SGJFWirQ3ks', icon='fa-s15', template='blocks/embed_block.html'))], blank=True, null=True, verbose_name='Wram Up'),
        ),
    ]
