# Generated by Django 2.2.7 on 2020-03-20 03:13

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_auto_20200320_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonunit',
            options={'ordering': ['title'], 'verbose_name': 'Lesson Unit', 'verbose_name_plural': 'Lesson Units'},
        ),
        migrations.RenameField(
            model_name='lessonunit',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='lessonunit',
            name='slug',
        ),
        migrations.AddField(
            model_name='lessonunit',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='lessonunit',
            name='objective',
            field=models.TextField(blank=True, help_text='objectives of the lesson', null=True),
        ),
        migrations.AlterField(
            model_name='lessondetail',
            name='breaktime',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Breaktime'),
        ),
        migrations.AlterField(
            model_name='lessondetail',
            name='section_1',
            field=wagtail.core.fields.StreamField([('heading_block', wagtail.core.blocks.StructBlock([('headting_text', wagtail.core.blocks.CharBlock(classname='title', required=True)), ('size', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))])), ('paragraph_block', wagtail.core.blocks.RichTextBlock(icon='fa-paragraph', template='blocks/paragraph_block.html')), ('image_block', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('attribution', wagtail.core.blocks.CharBlock(required=False))])), ('block_quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock()), ('attribute_name', wagtail.core.blocks.CharBlock(blank=True, label='e.g. Mary Berry', required=False))])), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL e.g https://www.youtube.com/embed/SGJFWirQ3ks', icon='fa-s15', template='blocks/embed_block.html'))], blank=True, null=True, verbose_name='Block 1'),
        ),
        migrations.AlterField(
            model_name='lessondetail',
            name='section_2',
            field=wagtail.core.fields.StreamField([('heading_block', wagtail.core.blocks.StructBlock([('headting_text', wagtail.core.blocks.CharBlock(classname='title', required=True)), ('size', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))])), ('paragraph_block', wagtail.core.blocks.RichTextBlock(icon='fa-paragraph', template='blocks/paragraph_block.html')), ('image_block', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('attribution', wagtail.core.blocks.CharBlock(required=False))])), ('block_quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock()), ('attribute_name', wagtail.core.blocks.CharBlock(blank=True, label='e.g. Mary Berry', required=False))])), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL e.g https://www.youtube.com/embed/SGJFWirQ3ks', icon='fa-s15', template='blocks/embed_block.html'))], blank=True, null=True, verbose_name='Block 2'),
        ),
        migrations.AlterField(
            model_name='lessondetail',
            name='warmup',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Warm Up'),
        ),
        migrations.AlterField(
            model_name='lessondetail',
            name='wrapup',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Wrap Up'),
        ),
        migrations.AlterField(
            model_name='lessonunit',
            name='description',
            field=models.TextField(blank=True, help_text='description of the lesson', null=True),
        ),
    ]
