# Generated by Django 2.2.7 on 2020-03-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0008_auto_20200320_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonunit',
            options={'verbose_name': 'Lesson Unit', 'verbose_name_plural': 'Lesson Units'},
        ),
        migrations.AlterField(
            model_name='lessonunit',
            name='content',
            field=models.TextField(blank=True, help_text='content of the lesson', null=True),
        ),
        migrations.AlterField(
            model_name='lessonunit',
            name='objective',
            field=models.TextField(blank=True, help_text='objective of the lesson', null=True),
        ),
    ]
