# Generated by Django 2.2.7 on 2020-03-20 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0009_auto_20200320_1040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonUnit',
        ),
    ]
