# Generated by Django 2.2.9 on 2020-01-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200105_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='division',
            field=models.CharField(choices=[('CD', 'Center'), ('AD', 'Academic'), ('OD', 'Operation')], default='CD', help_text="Select the person's division", max_length=2),
        ),
    ]
